### ISSUE TITLE
[HELP] My idiotic brain cant comprehend how you get the data

### ISSUE THREAD

**Issue by constantinDev** [Flumpster/botw-trainer#1]
Long story short: I have no idea how you load the data from the wii to the program. I took a fat look at the source code and couldn't figure out how you just get the results magically saved to "Weapons", "Bows" etc. Can you help me out here?

**Comment by TravisToastLord** [comment]
I have everything set up properly to use a botw trainer on my wiiu. I have all the dlc, mocha custom, tpc gecko (and I make sure to always type the right number in), and my wiiu firmware update is 5.5.1 USA. Please respond, every time I try to use this trainer it's like it doesn't detect the game at all.
